### ISSUE TITLE
YJ-14015 setup

### ISSUE THREAD

**Issue by joric** [jpconstantineau/NRF52-Board#1]
YJ-14015 is nRF51 but all the Adafruit nRF52 Arduino documentation is about nRF52, and s132 softdevice isn't compatible with nRF51 either. Is it supposed to use Arduino-nRF5 by Sandeep Mistry?

**Comment by jpconstantineau** [comment]
You are right. This isn't for the BlueMicro software which needs SoftDevice S132 and not S130.  

This hardware board is intended as a breakout board for the YJ14015 modules.
I have a few of these modules on hand but the current board has a problem with the module footprint.

**Comment by joric** [comment]
I've just managed to run [Arduino-nRF5 by Sandeep Mistry](https://github.com/sandeepmistry/arduino-nRF5) on a similar to YJ-14015 nRF51 chip (Waveshare Core51822 and BLE400 board with ST-Link v2, pretty generic) in arduino IDE, just followed instructions. Not sure there's a Bluefruit library but it works.

![](https://i.imgur.com/8dfPZFm.jpg)

BLE400 UART pins don't match your layout for some reason, it's RX-P05, TX-P06, CTS-P07, RTS-P12.

![](https://i.imgur.com/A9QIN2j.jpg)

Onboard USB works via CP2102, I guess it's hardwired to the same UART pins.

I guess UART isn't for uploading sketches as they get uploaded via ST-Link so we don't really need UART on keyboards. I have a fully assembled Mitosis I'm sure it will work as well. It'd be sweet to program it in Arduino IDE. I just have to figure out what API and what libraries does that repository use.

**Comment by joric** [comment]
Managed to make it work as a HID keyboard using unmodified HID sample from https://github.com/sandeepmistry/arduino-BLEPeripheral and get output from the BLE400 built in UART. So yeah, it's all very doable. I'll post my progress at https://github.com/joric/mitosis/tree/devel/
